---
name: Cypress Tests

on: push

jobs:
  cypress:
    name: Cypress e2e
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: Update hosts
        run: echo 127.0.0.1 lity.test | sudo tee -a /etc/hosts

      - name: Yarn Install
        run: sudo yarn install

      - name: Install WordPress
        run: |
          sudo apt-get update --allow-releaseinfo-change && sudo apt-get install -y subversion default-mysql-client
          mkdir -p /tmp/wordpress
          ./vendor/bin/wp core download --version=latest --path=/tmp/wordpress
          ./vendor/bin/wp config create --dbhost=127.0.0.1 --dbname=lity --dbuser=root --dbpass=password --path=/tmp/wordpress
          ./vendor/bin/wp db create --path=/tmp/wordpress
          ./vendor/bin/wp core install --url="http://lity.test" --title=Lity --admin_user=admin --admin_password=password --admin_email=test@admin.com --skip-email --path=/tmp/wordpress

      - name: Activate Lity
        run: |
          pwd
          yarn min
          sudo mkdir -p ./build/lity
          sudo rsync -av --exclude-from .distignore --delete . ./build/lity/
          mv ./build/lity /tmp/wordpress/wp-content/plugins/lity-testing
          ./vendor/bin/wp plugin activate lity-testing --path=/tmp/wordpress

      - name: Start WPCLI Server
        run: sudo ./vendor/bin/wp server --host=0.0.0.0 --port=80 --allow-root  --path=/tmp/wordpress &

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: ./node_modules/.bin/cypress run --config integrationFolder=./ --browser chrome --record --group e2e-chrome --headed
