---
name: Cypress - New

on: [push, pull_request]

jobs:
  cypress:
    name: Cypress e2e - (PHP ${{ matrix.php }} - WP ${{ matrix.wp }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4]
        wp: [5.0, 'latest']

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: lity
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php }}'
          extensions: mysql, zip
          coverage: none
          tools: composer, wp-cli

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Use Composer cache
        uses: actions/cache@master
        with:
          path: ${{ steps['composer-cache'].outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: COMPOSER_ROOT_VERSION=dev-master composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare test database
        run: |
          sudo apt-get update --allow-releaseinfo-change && sudo apt-get install -y subversion default-mysql-client
          mkdir -p /tmp/wordpress
          ./vendor/bin/wp core download --version=latest --path=/tmp/wordpress
          ./vendor/bin/wp config create --dbhost=127.0.0.1 --dbname=lity --dbuser=root --dbpass=password --path=/tmp/wordpress
          ./vendor/bin/wp db create --path=/tmp/wordpress
          ./vendor/bin/wp core install --url="http://lity.test" --title=Lity --admin_user=admin --admin_password=password --admin_email=test@admin.com --skip-email --path=/tmp/wordpress
          ./vendor/bin/wp rewrite structure '/%postname%'
          cp -R ${{ github.workspace }} /tmp/wordpress/wp-content/plugins/lity
          ./vendor/bin/wp plugin activate lity-testing --path=/tmp/wordpress
        env:
          WP_VERSION: ${{ matrix.wp }}

      - name: Start PHP server
        run: nohup php -S localhost:8080 > php.log 2>&1 &

      - name: Install yarn packages
        run: yarn install
        env:
          CYPRESS_INSTALL_BINARY: "0"

      # https://github.com/bahmutov/cypress-gh-action-split-install
      - name: Cypress cache 1
        run: npx cypress cache path && npx cypress cache list

      - name: Cypress cache 2
        id: cache-cypress
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-v1-${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Run Cypress
        run: npx cypress install && npx cypress cache list
      - uses: cypress-io/github-action@v2
        with:
          install: false
        env:
          CYPRESS_baseUrl: http://localhost:8080/index.php

      - name: Cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Cypress videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
