---
name: ESLint

on: push

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: Yarn Install
        run: sudo yarn install

      - name: Run eslint
        run: yarn lint:js
