name: PHPUnit Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: Scarlett
        with:
          bootstrap: .dev/tests/php/bootstrap.php
          configuration: phpunit.xml
          args: --coverage-text
