---
name: PHPUnit Tests

on: push

jobs:
  phpunit:
    name: PHPUnit - (PHP ${{ matrix.php }} - WP ${{ matrix.wp }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0]
        wp: ['5.6', 'latest']

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php }}'
          extensions: mysql, zip
          coverage: xdebug
          tools: composer, wp-cli

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Use Composer cache
        uses: actions/cache@master
        with:
          path: ${{ steps['composer-cache'].outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer Install
        run: |
          if [ "${{ env.WP_VERSION }}" == '5.6' ]; then
            sudo composer require phpunit/phpunit:^7.5.20 -W --dev
          fi
          sudo composer install
        env:
          WP_VERSION: ${{ matrix.wp }}

      - name: Install Tests - WordPress ${{ env.WP_VERSION }}
        run: |
          .dev/scripts/install-wp-tests.sh wordpress_test root password 127.0.0.1 ${{ env.WP_VERSION }}
          ./vendor/bin/wp config create --dbhost=127.0.0.1 --dbname=wordpress_test --dbuser=root --dbpass=password --path=/tmp/wordpress
        env:
          WP_VERSION: ${{ matrix.wp }}

      - name: Run unit tests
        run: |
          if [ "${{ env.WP_VERSION }}" == 8.0 &&  "${{ env.WP_VERSION }}" == 'latest' ];
            ./vendor/bin/phpunit --coverage-clover=clover.xml --log-junit=junit.xml
          then
            yarn test:php
          fi
        env:
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wp }}

      - name: Comment Unit Test Results on PR
        uses: EnricoMi/publish-unit-test-result-action@v1.39
        if: always()
        with:
          files: "junit.xml"

      - name: Publish Unit Test Results to Code Climate
        uses: aktions/codeclimate-test-reporter@v1
        with:
          codeclimate-test-reporter-id: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
          command: after-build --coverage-input-type clover
