name: PHPUnit Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD:
          MYSQL_ROOT_PASSWORD:
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: Install Tests
        run: yarn install:tests

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: Scarlett
        with:
          bootstrap: .dev/tests/php/bootstrap.php
          configuration: phpunit.xml
          args: --coverage-text
