---
name: Pre-Release

on:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install yarn dependencies
        run: yarn install

      - name: Build the plugin
        run: |
          yarn min
          rm -rf build/*
          sudo mkdir -p /build/lity
          rsync -av --mkpath --exclude-from .distignore --delete . build/lity/ && cd build/
          zip -r lity.zip lity/.

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: build/lity.zip
