---
name: Stylelint

on: push

jobs:
  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: Composer Install
        run: sudo composer install

      - name: Run unit eslint
        run: yarn lint:css
